/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author mateo
 */
public class VentanaCreditos extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaCreditos
     */
    public VentanaCreditos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAgradecimientos = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Creditos");

        jLabelAgradecimientos.setText("<html>\n    <div style='text-align: center;'>\n        <h2>Sobre el Proyecto</h2>\n        <p>\n            Este juego es una tarea entregable de la materia de Desarrollo de Interfaces,<br>\n            desarrollada por Mateo Carballo y Luis.\n        </p>\n        <p>\n            En ella presentamos un juego de memoria para demostrar los conocimientos adquiridos en la materia.<br>\n            Para esto utilizamos varios Internal Frames para cada una de las funcionalidades.\n        </p>\n        <p>\n            Los usuarios de la aplicación deberán registrarse a través de un formulario.<br>\n            Una vez registrados, deberán introducir sus credenciales para acceder al juego y poder guardar sus registros.\n        </p>\n        <p>\n            Si quieres profundizar más en cómo jugar,<br>\n            ve a la sección de Ayuda donde encontrarás una explicación detallada sobre el funcionamiento del juego.\n        </p>\n    </div>\n</html>\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabelAgradecimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelAgradecimientos, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAgradecimientos;
    // End of variables declaration//GEN-END:variables
}
