package vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Mateo
 */
public class VentanaPrimerosPasos extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaPrimerosPasos
     */
    public VentanaPrimerosPasos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelExplicacionJuego = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Primeros pasos");

        jLabelExplicacionJuego.setText("<html>\n    <div style='text-align: center;'>\n        <h2>Bienvenido al Juego de Memoria</h2>\n        <p>Este juego consiste en recordar la posición de las cartas para formar parejas iguales.</p>\n        <p>\n            Al comenzar, podrás ver las imágenes durante unos segundos.<br>\n            Luego todas se ocultarán con una imagen de interrogación.\n        </p>\n        <p>\n            Deberás hacer clic en dos cartas para voltearlas.<br>\n            - Si son iguales, quedarán descubiertas.<br>\n            - Si no son iguales, se ocultarán de nuevo.\n        </p>\n        <p>\n            El objetivo es encontrar todas las parejas en el menor tiempo posible.<br>\n            ¡Tu tiempo se registrará para la tabla de clasificación!\n        </p>\n        <br>\n        <p><b>¡Mucha suerte y a disfrutar!</b></p>\n    </div>\n</html>\n");
        jLabelExplicacionJuego.setToolTipText("Explicación juego");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jLabelExplicacionJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabelExplicacionJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelExplicacionJuego;
    // End of variables declaration//GEN-END:variables
}
